### ISSUE TITLE
ImportError: cannot import name bigquery_storage_v1beta1 from google.cloud

### ISSUE THREAD

**Issue by vanessanielsen** [googleapis/python-bigquery#206]
This error occurs when I run a query using %%bigquery magics in GCP-hosted notebook and the query fails.

"ImportError: cannot import name bigquery_storage_v1beta1 from google.cloud (unknown location)"

#### Environment details

  - OS type and version:
  - Python version: 3.7
  - pip version: 20.1.1
  - `google-cloud-bigquery` version: 1.26.0 and 1.26.1; not an issue with 1.25.0

#### Steps to reproduce

  1. Install current version of google-cloud-bigquery
  2. Query

#### Code example
```
%pip install --upgrade google-cloud-bigquery[bqstorage,pandas]
%load_ext google.cloud.bigquery
import google.cloud.bigquery.magics

%%bigquery stackoverflow --use_bqstorage_api
SELECT
  CONCAT(
    'https://stackoverflow.com/questions/',
    CAST(id as STRING)) as url,
  view_count
FROM `bigquery-public-data.stackoverflow.posts_questions`
WHERE tags like '%google-bigquery%'
ORDER BY view_count DESC
LIMIT 10
```

#### Stack trace

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-29432a7a9e7c> in <module>
----> 1 get_ipython().run_cell_magic('bigquery', 'stackoverflow --use_bqstorage_api', "SELECT\n  CONCAT(\n    'https://stackoverflow.com/questions/',\n    CAST(id as STRING)) as url,\n  view_count\nFROM `bigquery-public-data.stackoverflow.posts_questions`\nWHERE tags like '%google-bigquery%'\nORDER BY view_count DESC\nLIMIT 10\n")

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py in run_cell_magic(self, magic_name, line, cell)
   2369             with self.builtin_trap:
   2370                 args = (magic_arg_s, cell)
-> 2371                 result = fn(*args, **kwargs)
   2372             return result
   2373 

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/magics.py in _cell_magic(line, query)
    589             )
    590         else:
--> 591             result = query_job.to_dataframe(bqstorage_client=bqstorage_client)
    592 
    593         if args.destination_var:

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/job.py in to_dataframe(self, bqstorage_client, dtypes, progress_bar_type, create_bqstorage_client, date_as_object)
   3381             progress_bar_type=progress_bar_type,
   3382             create_bqstorage_client=create_bqstorage_client,
-> 3383             date_as_object=date_as_object,
   3384         )
   3385 

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/table.py in to_dataframe(self, bqstorage_client, dtypes, progress_bar_type, create_bqstorage_client, date_as_object)
   1725                 progress_bar_type=progress_bar_type,
   1726                 bqstorage_client=bqstorage_client,
-> 1727                 create_bqstorage_client=create_bqstorage_client,
   1728             )
   1729             df = record_batch.to_pandas(date_as_object=date_as_object)

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/table.py in to_arrow(self, progress_bar_type, bqstorage_client, create_bqstorage_client)
   1543             record_batches = []
   1544             for record_batch in self._to_arrow_iterable(
-> 1545                 bqstorage_client=bqstorage_client
   1546             ):
   1547                 record_batches.append(record_batch)

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/table.py in _to_page_iterable(self, bqstorage_download, tabledata_list_download, bqstorage_client)
   1432     ):
   1433         if bqstorage_client is not None:
-> 1434             for item in bqstorage_download():
   1435                 yield item
   1436             return

/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/_pandas_helpers.py in _download_table_bqstorage(project_id, table, bqstorage_client, preserve_order, selected_fields, page_to_item)
    626     # is available and can be imported.
    627     from google.cloud import bigquery_storage_v1
--> 628     from google.cloud import bigquery_storage_v1beta1
    629 
    630     if "$" in table.table_id:

ImportError: cannot import name 'bigquery_storage_v1beta1' from 'google.cloud' (unknown location)
```

**Comment by plamut** [comment]
@vanessanielsen Thanks for the report, the import error happens here:

https://github.com/googleapis/python-bigquery/blob/master/google/cloud/bigquery/_pandas_helpers.py#L625-L628

It's a bit weird, though, because you upgraded the library with the `bqstorage` dependency, but I was not able to reproduce the error in a fresh virtual environment after installing `google-cloud-bigquery-storage`:
```
$ python3.7 -m venv py-3.7
$ . py-3.7/bin/activate                                                                                                                                                                                                                                                                                                                                                                               
(py-3.7) $ python -m pip install google-cloud-bigquery-storage  
(py-3.7) $ python
Python 3.7.0+ (heads/3.7:ba1810e, Jul 23 2018, 14:37:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from google.cloud import bigquery_storage_v1
>>> from google.cloud import bigquery_storage_v1beta1
>>> 
```

Does the import error also happen if you try to import dependencies directly from IPython? It might be that the dependencies were installed in a _different_ Python than the one used by your IPython session, or maybe the kernel needs to be restarted?
```
In [1]: from google.cloud import bigquery_storage_v1 

In [2]: from google.cloud import bigquery_storage_v1beta1
```

Also, just to make sure, what is the output of the following?
```
In [3]: %pip show google-cloud-bigquery-storage  
```

Thanks for the info in advance!

**Comment by ekaputra07** [comment]
@plamut I got exactly the same issue today, here's the output:
```
%pip show google-cloud-bigquery-storage

Name: google-cloud-bigquery-storage
Version: 1.0.0
Summary: BigQuery Storage API API client library
Home-page: https://github.com/googleapis/python-bigquery-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: google-api-core
Required-by: 
```

I trying to run the `BigQuery basics.ipynb` on the GCP hosted JupyterLab

**Comment by plamut** [comment]
@ekaputra07 Hmm, it might be an environment issue then, as it seems weird that importing `bigquery_storage_v1` would succeed, but then on the very next line importing `bigquery_storage_v1beta1` from the same package would fail.

@shollyman Any idea why this could happen, since installing `google-cloud-bigquery-storage` locally installs both `v1` and `v1beta1` APIs? If there exist environment specifics that affect GCP hosted `JupyterLab`, then the [assumption](https://github.com/googleapis/python-bigquery/blob/fee2ba80e338d093ee61565359268da91a5c9913/google/cloud/bigquery/_pandas_helpers.py#L626-L629) from the code is incorrect and we need to adjust the library accordingly.

**Comment by shollyman** [comment]
I'm unaware of anything specific.  If it was an old (pre-1.x) install, I'd expect the opposite problem: v1beta1 present, v1 missing.

Only significant change in packaging since 1.25.0 was https://github.com/googleapis/python-bigquery/pull/164, did something with api core change something about the google.cloud namespace?  Is google-cloud-core not present?

Checking internally to see if there's anything special about the environment.

**Comment by vanessanielsen** [comment]
Hi @plamut,

Here are the responses to the things you suggested I try:

**In [1]: from google.cloud import bigquery_storage_v1** 
-> I'm continuing to get the same error:
ImportError: cannot import name 'bigquery_storage_v1beta1' from 'google.cloud' (unknown location)

**from google.cloud import bigquery_storage_v1beta1**
-> Upon importing, I get the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-0a897fd5466a> in <module>
----> 1 from google.cloud import bigquery_storage_v1beta1

ImportError: cannot import name 'bigquery_storage_v1beta1' from 'google.cloud' (unknown location)
```

**In [3]: %pip show google-cloud-bigquery-storage**  
```
Name: google-cloud-bigquery-storage
Version: 1.0.0
Summary: BigQuery Storage API API client library
Home-page: https://github.com/googleapis/python-bigquery-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: google-api-core
Required-by: 
Note: you may need to restart the kernel to use updated packages.
```

Upon restarting the kernel, I get the same error messages. Let me know if I can provide any more information!

**Comment by plamut** [comment]
@vanessanielsen Thanks for the response.

I'm not all that familiar with Jupyter setup and configuration, as I only use it occasionally, but I do remember that sometimes packages are installed in a _different_ environment than the one being used by the kernel. I found a [thread](https://github.com/jupyter/notebook/issues/2359) with a similar problem reported, and one of the suggestions is to use `{sys.executable}` from within the notebook to select the "right" installer:

```
import sys
!{sys.executable} -m pip install -U google-cloud-bigquery[bqstorage,pandas]
```

Are there any differences in the paths printed by the following two commands (from within the notebook) ?
```
In [3]: !echo {sys.executable}
In [4]: !which pip
```

I would try to check this first just to make sure the ` google-cloud-bigquery-storage` is indeed installed in the right environment.

---

BTW, the `--use_bqstorage_api` option is deprecated, as BQ Storage client is now used by default. It is possible to switch back to the REST API client with the `--use_rest_api` option as a workaround - it's slower, but if not querying huge amounts of data, its performance could still be good enough.

**Comment by vanessanielsen** [comment]
Thanks, @plamut 

Yeah, after posting my question I realized that --use_bqstorage_api is deprecated, however I get the same error, even when that line is removed. Here is the output for the commands you suggested:

```
!echo {sys.executable}
/opt/conda/bin/python

!which pip
/opt/conda/bin/pip
```

It seems to be installed in the right environment. I continue to get the same error message with my query. In the same notebook instance, using the previous version (1.25.0) continues to work fine.

**Comment by plamut** [comment]
> I realized that --use_bqstorage_api is deprecated, however I get the same error, even when that line is removed

@vanessanielsen  BQ Storage Client is a default client as of version 1.26.0 ([release notes](https://github.com/googleapis/python-bigquery/releases/tag/v1.26.0)), but you can revert to the old default by specifying the `--use_rest_api` option as noted above.

Thanks for the details, it indeed seems that the environment is correct, which makes it even more puzzling why the BQ Storage import would fail... :confused: We'll continue investigating.

**Comment by c-gottavianoni** [comment]
I faced the same issue and solved it by installing the packages using conda instead of pip

`conda install -c conda-forge google-cloud-bigquery google-cloud-bigquery-storage pandas pyarrow`

**Comment by mkunzdc** [comment]
Iv'e encountered the exact issue vanessanielsen described, with same results, beginning just recently. I am using a GCP AI Notebook on the AI platform.  I attempted the suggested code by plamut and received the following errors/output:

```import sys
!{sys.executable} -m pip install -U google-cloud-bigquery[bqstorage,pandas]

ERROR: google-cloud-storage 1.29.0 has requirement google-resumable-media<0.6dev,>=0.5.0, but you'll have google-resumable-media 0.7.1 which is incompatible.

ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/conda/lib/python3.7/site-packages/google/cloud/__pycache__/operation.cpython-37.pyc'
Consider using the `--user` option or check the permissions.
```
plamut's other suggestions resulted in same results vanessanielsen posted. I also attempted the code by c-gottavianoni but received an [Errno 13] Permission denied. 

Thanks for looking into this.

**Comment by c-gottavianoni** [comment]
@mkdc761 You can try to sudo it :
`!sudo /opt/conda/bin/conda install -c conda-forge google-cloud-bigquery   google-cloud-bigquery-storage   pandas   pyarrow`

**Comment by mkdc761** [comment]
Unfortunately that did not work. After updating with the code you provided, I received this message: 
```
/opt/conda/lib/python3.7/site-packages/google/cloud/bigquery/client.py:407: UserWarning: Cannot create BigQuery Storage client, the dependency google-cloud-bigquery-storage is not installed.
  The dataset that the routine belongs to must already exist
```
Followed by this error: 
```
AttributeError: 'NoneType' object has no attribute 'transport'
```

**Comment by mkdc761** [comment]
I just got it to work. I first updated with: 
```
!sudo /opt/conda/bin/conda install -c conda-forge google-cloud-bigquery google-cloud-bigquery-storage pandas pyarrow --yes. 
```
followed by: 
```
%pip install google-cloud-bigquery. 
```

**Comment by srinathh** [comment]
Several of us have faced the same kind of issue with AI Notebooks in my organizations as there was some upgraded AI Notebook image that was deployed. We seem to be having an issue with google-cloud-bigquery v1.26.1 interacting with google-cloud-bigquery-storage v1.0.0. 

Versions v1.24.0 for BigQuery and v0.8.0 for the storage lib seem to work.

**Comment by srinathh** [comment]
As an update, we're finding internally that downgrading our libs in AI Notebooks to BQ client lib 1.25.0 or 1.26.0 seems to work with BQ storage lib 1.0 0 and 0.8.0.

It seems that there's some kind of a bug between BQ lib 1.26.1 and BQ Storage lib 1.0.0

**Comment by boguszewiczr** [comment]
In my case that helped:

```
pip install google-cloud-bigquery==1.24.0
Uninstalling google-cloud-bigquery-1.26.0:
      Successfully uninstalled google-cloud-bigquery-1.26.0
pip install pydata-google-auth==1.1.0
```

Then restart Jupyter kernel. 

So basically what I need to query public dataset from Jupyter Notebook in GCP AI Platform:

```
import pydata_google_auth
credentials = pydata_google_auth.get_user_credentials( ['https://www.googleapis.com/auth/cloud-platform'], )
from google.cloud import bigquery, bigquery_storage
from google.cloud.bigquery import magics
magics.context.credentials = credentials
client = bigquery.Client('project_id', credentials = credentials)

%%bigquery
SELECT name, SUM(number) as count
FROM `bigquery-public-data.usa_names.usa_1910_current`
GROUP BY name
ORDER BY count DESC
LIMIT 10

```

**Comment by tswast** [comment]
I just checked a fresh Python 3 AI Platform notebook, and they still have the incompatible versions installed.

```
import google.cloud.bigquery

google.cloud.bigquery.__version__
# '1.26.1'
```

```
import google.cloud.bigquery_storage_v1

google.cloud.bigquery_storage_v1.__version__
# '1.0.0'
```

**Comment by ablackmorescg** [comment]
Following on from @tswast, having just tried the same commands using a fresh Python 3 AI Platform notebook I am still getting `ImportError: cannot import name 'bigquery_storage_v1beta1' from 'google.cloud' (unknown location)`. Can't run the tutorials for BigQuery that are pre-installed.

```
import google.cloud.bigquery

google.cloud.bigquery.__version__
# '1.28.0'
```

```
import google.cloud.bigquery_storage_v1

google.cloud.bigquery_storage_v1.__version__
# '2.4.0'
```

**Comment by tswast** [comment]
I think this might be part of the issue: https://github.com/GoogleCloudPlatform/jupyter-extensions/issues/411

Although, the extension is pinned to 1.26, so it doesn't really make sense that they'd have 1.28 installed.

**Comment by meredithslota** [comment]
I tested creating a default AI Platform Notebook (now Vertex AI Workbench, I think) and attempted to replicate this issue. I could not; everything ran just fine in a fresh (default) Python 3 notebook. The pip show command gave me the following: 

```
%pip show google-cloud-bigquery-storage

Name: google-cloud-bigquery-storage
Version: 2.10.1
Summary: BigQuery Storage API API client library
Home-page: https://github.com/googleapis/python-bigquery-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /opt/conda/lib/python3.7/site-packages
Requires: google-api-core, libcst, proto-plus
Required-by: beatrix-jupyterlab
Note: you may need to restart the kernel to use updated packages.
```

Please let me know if this reoccurs, but I think this is, broadly, fixed.

**Comment by mab3321** [comment]
In My case it was versioning issue pandas,and bigQuery versions.
google-cloud-storage==2.12.0
google-cloud-bigquery==3.12.0
db-dtypes==1.1.1
pandas==1.4.4
Above works for me with Python 3.8.15
