### ISSUE TITLE
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)

### ISSUE THREAD

**Issue by hoshw** [googleapis/python-bigquery#70]
#### Environment details

  - OS type and version: 
MacOS
  - Python version: `python --version`. 
Python 2.7.16
  - pip version: `pip --version`. 
pip 20.0.2 
  - `google-cloud-bigquery` version: `pip show google-cloud-bigquery`

Name: google-cloud-bigquery
Version: 1.24.0
Summary: Google BigQuery API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages
Requires: protobuf, google-api-core, six, google-cloud-core, google-auth, google-resumable-media
Required-by: 

#### Steps to reproduce

  1.  from google.cloud import bigquery
  2. That fails with the message ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)

#### Local fix
I made the following change to 
/Library/Python/3.7/site-packages/google/cloud/bigquery/Schema.py

```
##from six.moves import collections_abc
try:
    from collections import abc as collections_abc
except ImportError:  # Python 2.7
    import collections as collections_abc
```

**Comment by HemangChothani** [comment]
@hoshw Could share the version of `six` library, i think it's working fine with the 1.14.0 version.

**Comment by hoshw** [comment]
when I print(six.__version__) it returns 1.12.0

!pip install --upgrade six tells me its already at 1.14
Requirement already up-to-date: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.14.0)

I think my Jupyter notebook is trapped between python worlds and gets confused...

**Comment by plamut** [comment]
@hoshw  Based on the information, it indeed appears that a different `six` version is imported and used in the notebook.

As a workaround, it might be easier to add a [custom rename](https://six.readthedocs.io/#advanced-customizing-renames) to the top of the notebook with `six.add_move()`, at least until you get to the bottom of the notebook's confusion. :)

**Comment by plamut** [comment]
@hoshw Any luck so far, did the suggestions help? Can this issue be closed?

**Comment by hoshw** [comment]
Its working for now because I edited bigquery/Schema.py. Thank you for your suggestion, if it breaks again in the future I'll use that approach. You can close the issue.

**Comment by Ark-kun** [comment]
> !pip install

I use a more bullet-proof command: `python3 -m pip install`
