### ISSUE TITLE
Biquery - bigquery_client.query() Attribute Error

### ISSUE THREAD

**Issue by Seldakao** [googleapis/python-bigquery#2]
I am fetching data from bigquery by using

from google.cloud import bigquery
...
def bigquery_to_df(query):
    '''A small tool to convert the result of Bigquery to DataFrame'''

    query_job = bigquery_client.query(query)
    df = query_job.result().to_dataframe()
    return df
...
But got AttributeError which I didn't get before 
     10     query_job = bigquery_client.query(query)
---> 11     df = query_job.result().to_dataframe()
     12     return df
     13 

AttributeError: 'HTTPIterator' object has no attribute 'to_dataframe'

#### Environment details
Mac Book Pro
I used to use google-cloud-bigquery 0.28.0 and it worked fine for a long time until now. And even after I upgraded to 1.24.0 now the error still occurs.

Does anyone encounter the same issue?

**Comment by plamut** [comment]
Weird, after moving the issue the bot removed @shollyman as the assignee, and it's not possible to re-assign him again in this repo.

**Comment by shollyman** [comment]
I'm going to close this one, as it seems like its tied to something in the local (or jupyter kernel) environment.  I don't know that we're going to be able to provide any meaningful updates here barring something we can more clearly reproduce.

If someone encounters this and get successfully articulate reproduction steps, please file an issue with those details.
